repos:
- repo: local
  hooks:
    - id: cloudformation-template-checks
      name: CloudFormation template checks
      entry: backend/scripts/pre_commit_cfn.sh
      language: script
      files: ^backend/template.yaml$

